### ISSUE TITLE
Problem with multiple query parameters

### ISSUE THREAD

**Issue by lpz** [riskfirst/riskfirst.restclient#7]
Calling:`uri.AsRestRequest().WithQueryParameter("a",1).WithQueryParameter("b",2);`
results in appending ** ??a=1&b=2** to URI and therefore not passing any parameters to API.
Same when using `WithQueryParameters(IDictionary<string, object> values)` with many keys.

**Comment by jamiecoh** [comment]
Hi thanks for the report. 

As you can see from the above commit associated we've added a couple of unit tests to try to reproduce this issue without much luck.

Could you provide the exact code you've used to illustrate the problem?

Thanks

**Comment by lpz** [comment]
looks like the problem only occurs when calling code is on .NET 4.7.1, identical code in Core 2.0 doesn't have this issue

**Comment by coldridj** [comment]
This is a .NET framework bug - it was fixed in net standard 1.1 with this commit: https://github.com/dotnet/corefx/commit/298fb7dc143c83a5535233cd8326dc8ae3c040c8#diff-ad99cf89e6bccc8f6f022f22f8de6aee but seems not to have been merged back to framework.

This means we will have to introduce the query string prefix test to work around this limitation.
